### ISSUE TITLE
Crash when cache evict

### ISSUE THREAD

**Issue by nemesisqp** [nats-io/nats-streaming-server#221]
this is my log
```
[5796] 2016/12/26 09:43:03.939862 [INF] Starting nats-streaming-server[Nerve-Hub] version 0.3.6
[5796] 2016/12/26 09:43:04.020973 [INF] Starting nats-server version 0.9.6
[5796] 2016/12/26 09:43:04.021950 [INF] Starting http monitor on 127.0.0.1:8222
[5796] 2016/12/26 09:43:04.025860 [INF] Listening for client connections on 0.0.0.0:4222
[5796] 2016/12/26 09:43:04.026837 [INF] Server is ready
[5796] 2016/12/26 09:43:04.303394 [INF] STAN: Message store is FILE
[5796] 2016/12/26 09:43:04.303394 [INF] STAN: --------- Store Limits ---------
[5796] 2016/12/26 09:43:04.307302 [INF] STAN: Channels:                 1000
[5796] 2016/12/26 09:43:04.308280 [INF] STAN: -------- channels limits -------
[5796] 2016/12/26 09:43:04.310234 [INF] STAN:   Subscriptions:          1000 *
[5796] 2016/12/26 09:43:04.311211 [INF] STAN:   Messages     :      10000000
[5796] 2016/12/26 09:43:04.313166 [INF] STAN:   Bytes        :     976.56 MB *
[5796] 2016/12/26 09:43:04.314143 [INF] STAN:   Age          :     unlimited *
[5796] 2016/12/26 09:43:04.318052 [INF] STAN: --------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x10 pc=0x517903]

goroutine 10 [running]:
panic(0x85b900, 0xc04200a090)
        /home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:500 +0x1af
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).evictFromCache(0xc042038340, 0x1493fbe46c0257d4)
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2174 +0xb3
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).backgroundTasks(0xc042038340)
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:1987 +0x3b1
created by github.com/nats-io/nats-streaming-server/stores.(*FileStore).newFileMsgStore
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:1252 +0xca5
```

**Comment by kozlovic** [comment]
@nemesisqp Thanks for the report. It's strange because the crash occurs in a place where I did not check for `cMsg` being nil because - and I put comment there - it should not be. There should be at least a message left in that part of code. The case where they all would be removed should be handled at line 2162.
Anyway, I am going to investigate that tomorrow. If you have a way to reproduce this, that would be appreciated. Thanks!

**Comment by nemesisqp** [comment]
I try to reproduce this crash and got one more log, there is one more line `Slow Consumer Detected` when I push around 16k msg nats server crash reliably with bellow log
```
7048] 2016/12/27 10:09:41.477593 [INF] Starting nats-streaming-server[Nerve-Hub] version 0.3.6
[7048] 2016/12/27 10:09:41.573362 [INF] Starting nats-server version 0.9.6
[7048] 2016/12/27 10:09:41.573362 [INF] Starting http monitor on 127.0.0.1:8222
[7048] 2016/12/27 10:09:41.580205 [INF] Listening for client connections on 0.0.0.0:4222
[7048] 2016/12/27 10:09:41.581181 [INF] Server is ready
[7048] 2016/12/27 10:09:41.856760 [INF] STAN: Message store is FILE
[7048] 2016/12/27 10:09:41.856760 [INF] STAN: --------- Store Limits ---------
[7048] 2016/12/27 10:09:41.860668 [INF] STAN: Channels:                 1000
[7048] 2016/12/27 10:09:41.862623 [INF] STAN: -------- channels limits -------
[7048] 2016/12/27 10:09:41.864576 [INF] STAN:   Subscriptions:          1000 *
[7048] 2016/12/27 10:09:41.865554 [INF] STAN:   Messages     :      10000000
[7048] 2016/12/27 10:09:41.867509 [INF] STAN:   Bytes        :     976.56 MB *
[7048] 2016/12/27 10:09:41.869464 [INF] STAN:   Age          :     unlimited *
[7048] 2016/12/27 10:09:41.876305 [INF] STAN: --------------------------------
[7048] 2016/12/27 10:14:12.208363 [INF] 14.161.79.238:56185 - cid:6 - Slow Consumer Detected
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x10 pc=0x517903]

goroutine 35 [running]:
panic(0x85b900, 0xc04200a090)
        /home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:500 +0x1af
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).evictFromCache(0xc04201eb60, 0x1493fe6ec25c75d8)
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2174 +0xb3
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).backgroundTasks(0xc04201eb60)
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:1987 +0x3b1
created by github.com/nats-io/nats-streaming-server/stores.(*FileStore).newFileMsgStore
        /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:1252 +0xca5
```

**Comment by nemesisqp** [comment]
It seem stream server will crash when client publisher reach default maxPubAcksInflight (16k) and consumer is slow processing 1 msg/s
How can I config nats streaming server as an shock absorber broker ?  I need it hold around 1 mil msg for queue group of slow consumer

**Comment by kozlovic** [comment]
@nemesisqp I have been able to reproduce the crash! Working on a fix right now. Thanks again!

**Comment by kozlovic** [comment]
@nemesisqp I found the bug, it was simply that the list was not properly updated during a lookup, when a message is moved to the end of the list (https://github.com/nats-io/nats-streaming-server/commit/be824fdb52474cb8a63e41b19c8736d0366e6449#diff-66e8d3e0dc21ac3febf69f370f5adad5R2156). If you have a chance to try the fix, that would be much appreciated!.

To answer your previous question, you should not have to do anything special configuration wise. This is what Streaming is supposed to accomplish.
