### ISSUE TITLE
Panic in file store

### ISSUE THREAD

**Issue by mackeyja92** [nats-io/nats-streaming-server#239]
Getting this in my docker container running nats-streaming.

v0.3.6

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5119cc]

goroutine 54 [running]:
panic(0x852760, 0xc420010030)
#011/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).evictFromCache(0xc4216ce4e0, 0x149a774c792d0369)
#011/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2174 +0xac
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).backgroundTasks(0xc4216ce4e0)
#011/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:1987 +0x3aa
created by github.com/nats-io/nats-streaming-server/stores.(*FileStore).newFileMsgStore
#011/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:1252 +0xc9e
```

**Comment by kozlovic** [comment]
This was already reported and fixed with: https://github.com/nats-io/nats-streaming-server/pull/222.
