### ISSUE TITLE
panic with --sql_no_caching

### ISSUE THREAD

**Issue by powerman** [nats-io/nats-streaming-server#618]
This command works fine without `--sql_no_caching`, but with this options it panics.
```
$ docker run -i -t --rm --name=nss -p 4222:4222 --link=mysql nats-streaming:0.10.2 --cluster_id=dev --store=SQL --sql_driver=mysql --sql_source='root:@tcp(mysql)/nss' --sql_no_caching -SDV
[1] 2018/07/12 12:48:59.676698 [INF] STREAM: Starting nats-streaming-server[dev] version 0.10.2
[1] 2018/07/12 12:48:59.676741 [INF] STREAM: ServerID: X5uCI58JEwfeWQ3ZBmprQ6
[1] 2018/07/12 12:48:59.676746 [INF] STREAM: Go version: go1.10.3
[1] 2018/07/12 12:48:59.680869 [INF] Starting nats-server version 1.1.0
[1] 2018/07/12 12:48:59.680891 [INF] Git commit [not set]
[1] 2018/07/12 12:48:59.681836 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2018/07/12 12:48:59.681843 [INF] Server is ready
[1] 2018/07/12 12:48:59.706006 [TRC] STREAM:  NATS conn opts: { [nats://127.0.0.1:4222] false _NSS-dev-send false false false <nil> true -1 250ms 2s 0s 2m0s 2 0x8e49b0 0x8e4a00 0x8e4960 <nil> 0x8e48f0 -1 8192    <nil> <nil> false}
[1] 2018/07/12 12:48:59.706325 [TRC] STREAM:  NATS conn opts: { [nats://127.0.0.1:4222] false _NSS-dev-general false false false <nil> true -1 250ms 2s 0s 2m0s 2 0x8e49b0 0x8e4a00 0x8e4960 <nil> 0x8e48f0 -1 8192    <nil> <nil> false}
[1] 2018/07/12 12:48:59.706559 [TRC] STREAM:  NATS conn opts: { [nats://127.0.0.1:4222] false _NSS-dev-acks false false false <nil> true -1 250ms 2s 0s 2m0s 2 0x8e49b0 0x8e4a00 0x8e4960 <nil> 0x8e48f0 -1 8192    <nil> <nil> false}
[1] 2018/07/12 12:48:59.706751 [INF] STREAM: Recovering the state...
[1] 2018/07/12 12:48:59.709505 [INF] STREAM: Shutting down.
[1] 2018/07/12 12:48:59.709720 [DBG] STREAM: connection "_NSS-dev-send" has been closed
[1] 2018/07/12 12:48:59.709739 [INF] Server Exiting..
[1] 2018/07/12 12:48:59.709756 [DBG] STREAM: connection "_NSS-dev-general" has been closed
[1] 2018/07/12 12:48:59.709768 [DBG] STREAM: connection "_NSS-dev-acks" has been closed
[1] 2018/07/12 12:48:59.709788 [INF] STREAM: Failed to start: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x83f844]

goroutine 1 [running]:
github.com/nats-io/nats-streaming-server/server.RunServerWithOpts.func1(0xc420230000, 0xc4201e5f50)
	/go/src/github.com/nats-io/nats-streaming-server/server/server.go:1428 +0x1c9
panic(0x9b8ac0, 0xdfa350)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/nats-io/nats-streaming-server/stores.(*SQLSubStore).recoverPendingRow(0xc420186460, 0xc42016dc00, 0xc4201864d0, 0x0, 0xc4205e0b70, 0x0, 0x0, 0x0)
	/go/src/github.com/nats-io/nats-streaming-server/stores/sqlstore.go:1955 +0x2c4
github.com/nats-io/nats-streaming-server/stores.(*SQLStore).Recover(0xc42029e000, 0x0, 0x0, 0x0)
	/go/src/github.com/nats-io/nats-streaming-server/stores/sqlstore.go:913 +0x122c
github.com/nats-io/nats-streaming-server/server.(*StanServer).start(0xc420230000, 0x0, 0x0, 0x0)
	/go/src/github.com/nats-io/nats-streaming-server/server/server.go:1602 +0x117
github.com/nats-io/nats-streaming-server/server.RunServerWithOpts(0xc420220000, 0xc420220240, 0x0, 0x0, 0x0)
	/go/src/github.com/nats-io/nats-streaming-server/server/server.go:1521 +0xca0
main.main()
	/go/src/github.com/nats-io/nats-streaming-server/nats-streaming-server.go:153 +0x4f
```

**Comment by kozlovic** [comment]
@powerman Very sorry about that. It is probably happening following a run without `-sql_no_caching`. I have submitted a PR that addresses this issue. Thank you for the report!
