### ISSUE TITLE
[HELP] STREAM: Failed to start: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by acro5piano** [nats-io/nats-streaming-server#872]
Hi, thank you for the great product.

I'm quite new to nats, so I'm sorry if my question does not make sense.

I would like to run nats-streaming-server with embedded nats-server in AWS EC2 instance, using TLS connection for external connections.
However, I cannot run nats-streaming-server in TLS mode.

If I run `nats-server` with TLS related option, it works perfectly:

```
[ec2-user@ip-xxx example.com]$ nats-server -DV --tlscert /etc/letsencrypt/live/example.com/fullchain.pem --tlskey /etc/letsencrypt/live/example.com/privkey.pem
[29448] 2019/07/02 17:56:30.694947 [INF] Starting nats-server version 2.0.0
[29448] 2019/07/02 17:56:30.695026 [DBG] Go build version go1.11.10
[29448] 2019/07/02 17:56:30.695063 [INF] Git commit [not set]
[29448] 2019/07/02 17:56:30.695184 [INF] Listening for client connections on 0.0.0.0:4222
[29448] 2019/07/02 17:56:30.695229 [INF] TLS required for client connections
[29448] 2019/07/02 17:56:30.695262 [INF] Server id is NBOVZUMJ2FP5WXPHWANVHK5LTNI32FUN2QNJW36SAVBDQ5D5ISB2KVJC
[29448] 2019/07/02 17:56:30.695300 [INF] Server is ready
[29448] 2019/07/02 17:56:30.695337 [DBG] Get non local IPs for "0.0.0.0"
[29448] 2019/07/02 17:56:30.695514 [DBG]  ip=172.31.41.101
```

However, if I run `nats-streaming-server` with TLS related option, it doesn't work:

```
[ec2-user@ip-xxx example.com]$ nats-streaming-server -DV --tlscert /etc/letsencrypt/live/example.com/fullchain.pem --tlskey /etc/letsencrypt/live/example.com/privkey.pem
[29442] 2019/07/02 17:55:07.363115 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.15.1
[29442] 2019/07/02 17:55:07.363197 [INF] STREAM: ServerID: Pp6vQqnip7TWMtPYkJhVVx
[29442] 2019/07/02 17:55:07.363238 [INF] STREAM: Go version: go1.11.10
[29442] 2019/07/02 17:55:07.363285 [INF] STREAM: Git commit: [not set]
[29442] 2019/07/02 17:55:07.364406 [INF] Starting nats-server version 2.0.0
[29442] 2019/07/02 17:55:07.364489 [DBG] Go build version go1.11.10
[29442] 2019/07/02 17:55:07.364523 [INF] Git commit [not set]
[29442] 2019/07/02 17:55:07.364670 [INF] Listening for client connections on 0.0.0.0:4222
[29442] 2019/07/02 17:55:07.364735 [INF] TLS required for client connections
[29442] 2019/07/02 17:55:07.364766 [INF] Server id is NAGUVTD7TNNO3NDUYVHS47Y34IERGJ6V6KDZGWSA35X24ZTJFP5C3WRZ
[29442] 2019/07/02 17:55:07.364799 [INF] Server is ready
[29442] 2019/07/02 17:55:07.364835 [DBG] Get non local IPs for "0.0.0.0"
[29442] 2019/07/02 17:55:07.365019 [DBG]  ip=172.31.41.101
[29442] 2019/07/02 17:55:07.389894 [DBG] 127.0.0.1:45200 - cid:1 - Client connection created
[29442] 2019/07/02 17:55:07.390222 [DBG] 127.0.0.1:45200 - cid:1 - Starting TLS client connection handshake
[29442] 2019/07/02 17:55:07.416825 [INF] STREAM: Shutting down.
[29442] 2019/07/02 17:55:07.417526 [INF] Server Exiting..
[29442] 2019/07/02 17:55:07.417618 [DBG] 127.0.0.1:45200 - cid:1 - Client connection closed
[29442] 2019/07/02 17:55:07.417736 [ERR] 127.0.0.1:45200 - cid:1 - TLS handshake error: remote error: tls: bad certificate
[29442] 2019/07/02 17:55:07.417818 [FTL] STREAM: Failed to start: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```

I added `-tls_client_key` and `-tls_client_cert` but no luck.

Can I use nats-streaming-server without TLS only for embedded nats?
I don't think we need to encrypt communication between nats-streaming-server and its embbed nats-server because the two are in the same machine.

Thank you,

**Comment by kozlovic** [comment]
Look at the error message. The issue is that the NATS Streaming server attempts a connection using `127.0.0.1` to the embedded NATS Server, but the certificate is such that it cannot validate with that hostname (since certificate does not have this IP in the list of SANs).
So you could try any of those approaches:
- Add 127.0.0.1 in your cert's SANs
- If the cert has a public IP in the SANs, use that IP when starting the server (with `-a "<public IP>"`)
- Run the NATS Server separately and have NATS Streaming server connect to it using `-ns nats://<nats server host>:<port>` where the hostname is valid based on the certificate.

**Comment by kozlovic** [comment]
As another option:
- Use the hostname that is in the certificate as the host `-a <hostname>`

The idea is that this is what you want the server to use for the internal connection to the embedded server. If you start without `-a` it defaults to 0.0.0.0 for listen port and 127.0.0.1 for internal connection. If an explicit host is specified with `-a`, then this is what will be used.

**Comment by acro5piano** [comment]
Hi, thank you for quick response. I really appreciate your help!

> - Run the NATS Server separately and have NATS Streaming server connect to it using -ns nats://<nats server host>:<port> where the hostname is valid based on the certificate.

I finally success to pub/sub event via that option. Thank you very much!

```
[ec2-user@ip-xxx example.com]$ nats-server -DV --tlscert /etc/letsencrypt/live/example.com/fullchain.pem --tlskey /etc/letsencrypt/live/example.com/privkey.pem
```

```
[ec2-user@ip-xxx example.com]$ nats-streaming-server -DV -ns tls://example.com:4222
```

# Logs

The followings are what I tried. I shall leave them here for the future beginners.

> - Add 127.0.0.1 in your cert's SANs

Unfortunately I couldn't find how to accomplish it. It seems that I don't have enough knowledge about ssl.

> - If the cert has a public IP in the SANs, use that IP when starting the server (with -a "<public IP>")

Assuming the public IP is `52.xxx.yy.zz`, I tried but failed:

```
[ec2-user@ip-172-31-41-101 example.com]$ nats-streaming-server -DV --tlscert /etc/letsencrypt/live/nats-stg.nupp1.io/fullchain.pem --tlskey /etc/letsencrypt/live/nats-stg.nupp1.io/privkey.pem -a 52.xxx.yy.zz
[30189] 2019/07/02 18:49:54.326258 [FTL] Error listening on port: 52.xxx.yy.zz:4222, "listen tcp 52.xxx.yy.zz:4222: bind: cannot assign requested address"
```

> - Run the NATS Server separately and have NATS Streaming server connect to it using -ns nats://<nats server host>:<port> where the hostname is valid based on the certificate.

It seems working, but when I connect to nats-server from JavaScript Client, it says `Unhandled error. (stan: connect request timeout)`

```typescript
import Stan from 'node-nats-streaming'

const stan = Stan.connect('foo', 'bar', {  // <--- here is wrong
  url: process.env.NATS_URL,
  token: process.env.NATS_TOKEN,
})

stan.on('connect', function() {
  // Simple Publisher (all publishes are async in the node version of the client)
  stan.publish('foo', 'Hello node-nats-streaming!', function(err, guid) {
    if (err) {
      console.log('publish failed: ' + err)
    } else {
      console.log('published message with guid: ' + guid)
    }
  })

  // Subscriber can specify how many existing messages to get.
  var opts = stan.subscriptionOptions().setStartWithLastReceived()
  var subscription = stan.subscribe('foo', opts)
  subscription.on('message', function(msg) {
    console.log('Received a message [' + msg.getSequence() + '] ' + msg.getData())
  })

  // After one second, unsubscribe, when that is done, close the connection
  setTimeout(function() {
    subscription.unsubscribe()
    subscription.on('unsubscribed', function() {
      stan.close()
    })
  }, 1000)
})
```

```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (stan: connect request timeout)
    at Stan.emit (events.js:171:17)
    at Stan.EventEmitter.emit (domain.js:442:20)
    at Stan.closeWithError (/Users/kazuya/ghq/github.com/llotheo/nupp1-payment-service/node_modules/node-nats-streaming/lib/stan.js:417:10)
    at Object.nc.requestOne [as callback] (/Users/kazuya/ghq/github.com/llotheo/nupp1-payment-service/node_modules/node-nats-streaming/lib/stan.js:328:22)
    at Timeout.conf.timeout.setTimeout (/Users/kazuya/ghq/github.com/llotheo/nupp1-payment-service/node_modules/nats/lib/nats.js:1822:22)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

I found my mistake here, I launched `nats-streaming-server` without specifying `--cluster_id foo`, so cluster id of nats-streaming-server was `test-cluster` which is the default name.

**Comment by kozlovic** [comment]
@acro5piano Glad you have all this figured out. Yes, the connect call should use the cluster ID of the streaming server one. Also, note that `-DV` is for NATS Server. If you want to have Streaming specific debug/trace, use `-SDV`. When you embed NATS Server, you can of course combine both if you want both NATS and STAN debug/trace `-SDV -DV`. Note that those will produce lots of output so this should not be used in prod env.

**Comment by acro5piano** [comment]
@kozlovic Thank you for your advise! I will remove the `-DV` option when I use them in production mode.
